### ISSUE TITLE
[Doc] ảnh lỗi

### ISSUE THREAD

**Issue by NNBnh** [20021515/FlappyChim-2.0#2]
![Screenshot_2021-05-17 20021515 FlappyChim-2 0](https://user-images.githubusercontent.com/43980777/118447255-c362d900-b71a-11eb-8b27-255ff54bd09e.png)

**Comment by NNBnh** [comment]
#3 merge cái này đi ;)

**Comment by DuCLeK65t** [comment]
oke chưa?
